### ISSUE TITLE
Clean up buttons don't work. Playback breaks

### ISSUE THREAD

**Issue by alexjabka** [Jetpack-Crow/autogrip#8]
Hi. First time reporting on something. Great addon. But buggy:

**1.** Clean up buttons don't work (some error about no "scene" pops up) 

```
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\autogrip-main\handrig.py", line 1023, in execute
    reset_hand(righthandroot)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\autogrip-main\handrig.py", line 918, in reset_hand
    scene = context.scene
AttributeError: '_RestrictContext' object has no attribute 'scene'
```

**2.** It sometimes somehow bugs up animation playback of other shrinkwrap bones that I have on another models. Like it works fine but playback breaks when there are keyframes on IK bones. By buggy playback I mean that shrinkwrap bones go wild or offset in play time lagging behing body. I managed to get playback back to normal by switching to blender 3.3.1, appending everything, saving .blend file and opening with blender 3.4.0 again but the issue comes back after a while.

Also, I wanted to dono but ko-fi is paypal only. I can't use paypal, sorry.

**Comment by alexjabka** [comment]
Playback issue seems gone idk what I did, it just disappeared.

**Comment by alexjabka** [comment]
Ahhh. Hello again, the 2nd issue is solved... I found out why playback was buggy: I had 20 dependency cycles because of existing shrinkwrap bones on another character lul.

**Comment by Jetpack-Crow** [comment]
Whoops! Yeah, dependency cycles would do it! But I'll see what I can do about the cleanup buttons in the new version.

**Comment by Jetpack-Crow** [comment]
Finally came back to spend a little bit of time on this - the cleanup buttons should work now! I didn't need to be calling scene anyway.
